services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Hello123
      MYSQL_DATABASE: audio
      MYSQL_USER: hxben
      MYSQL_PASSWORD: Hello123
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    # command: --skip-grant-tables --skip-networking

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Hello123
    ports:
      - "8080:80"